### ISSUE TITLE
motr/config.h must be included by Motr API users

### ISSUE THREAD

**Issue by andriytk** [Seagate/cortx-motr#1212]
`motr/config.h` header has to be included by apps which use Motr API - which is pretty inconvenient. We can do better - include it automatically from the public headers which need it.

**Comment by cortx-admin** [comment]
For the convenience of the Seagate development team, this issue has been mirrored in a private Seagate Jira Server: https://jts.seagate.com/browse/EOS-26105. Note that community members will not be able to access that Jira server but that is not a problem since all activity in that Jira mirror will be copied into this GitHub issue.

**Comment by cortx-admin** [comment]
> Nagakishore Kommuri commented in Jira Server:

Github issue closed

**Comment by cortx-admin** [comment]
> Nagakishore Kommuri commented in Jira Server:

.

**Comment by cortx-admin** [comment]
> Nagakishore Kommuri commented in Jira Server:

.
