### ISSUE TITLE
Extend ISC demo with another min/max example

### ISSUE THREAD

**Issue by andriytk** [Seagate/cortx-motr#1213]
Extend ISC demo with another min/max example, for the case when the data is stored as 8-byte double numbers arrays.

**Comment by cortx-admin** [comment]
For the convenience of the Seagate development team, this issue has been mirrored in a private Seagate Jira Server: https://jts.seagate.com/browse/EOS-26106. Note that community members will not be able to access that Jira server but that is not a problem since all activity in that Jira mirror will be copied into this GitHub issue.

**Comment by chandradharraval** [comment]
@andriytk - I see you have linked https://github.com/Seagate/cortx-motr/pull/1214 with is in draft state? What would be next actions for these tickets?

**Comment by andriytk** [comment]
I might complete it someday when I have time.

**Comment by cortx-admin** [comment]
> Chandradhar Raval commented in Jira Server:

Hi [~520414],

Is there any further update on taking this draft PR to next stage?

**Comment by cortx-admin** [comment]
> Chandradhar Raval commented in Jira Server:

Marking this issue Closed as corresponding github is addressed via [https://github.com/Seagate/cortx-motr/pull/1214]
