### ISSUE TITLE
Need to add correct word in cortx-motr main page

### ISSUE THREAD

**Issue by imvenkip** [Seagate/cortx-motr#1241]
onfigurations. To ensure the most efficient storage utilization, Motr interacts directly with block devices (i.e. it does not _layer_ on a local file system). The Motr design was heavily influenced by the Lustre file system, NFSv4 and database technology. It must be noted that traditional file system properties (hierarchical directory namespace, strong POSIX consistency guarantees, **&c.)** are no longer des.

https://github.com/Seagate/cortx-motr

It is added "&c".  I am not sure , may be it is a "etc.."

**Comment by cortx-admin** [comment]
For the convenience of the Seagate development team, this issue has been mirrored in a private Seagate Jira Server: https://jts.seagate.com/browse/EOS-26544. Note that community members will not be able to access that Jira server but that is not a problem since all activity in that Jira mirror will be copied into this GitHub issue.

**Comment by r-wambui** [comment]
@novium258 @swatid-seagate Could you please take a look at this.

**Comment by cortx-admin** [comment]
> Nagakishore Kommuri commented in Jira Server:

Github issue closed

**Comment by cortx-admin** [comment]
> Nagakishore Kommuri commented in Jira Server:

.

**Comment by cortx-admin** [comment]
> Nagakishore Kommuri commented in Jira Server:

.
