### ISSUE TITLE
Improve API to switch m0trace completely off at startup time

### ISSUE THREAD

**Issue by andriytk** [Seagate/cortx-motr#1317]
Currently, there is `m0_trace_set_mmapped_buffer(false)` API which disables the creation of mmap-ped file with the tracing buffer, but it does not disable the tracing - which still might be the bottleneck and kill the concurrency when many threads are used in the process. (Note: tracing uses the atomic variable for records allocation, which is kills scalability.)

Suggestion: improve `m0_trace_set_mmapped_buffer(false)` API to switch tracing completely OFF.

**Comment by cortx-admin** [comment]
For the convenience of the Seagate development team, this issue has been mirrored in a private Seagate Jira Server: https://jts.seagate.com/browse/EOS-26950. Note that community members will not be able to access that Jira server but that is not a problem since all activity in that Jira mirror will be copied into this GitHub issue.

**Comment by andriytk** [comment]
Implemented by #1319.

**Comment by cortx-admin** [comment]
> Chandradhar Raval commented in Jira Server:

Marking this issue Closed as per above comments
