### ISSUE TITLE
Resources unavailable in the public doc

### ISSUE THREAD

**Issue by rkothiya** [Seagate/cortx-motr#1357]
While trying to follow the "[Cortx Manual Deployment 1 Node VM Factory and Field](https://seagate-systems.atlassian.net/wiki/spaces/PUB/pages/604438718/CORTX+Manual+Deployment+onto+1+Node+VM+Factory+and+Field
)" we are unable to access the link used for installation.

Also the path mentioned in the curl command needs to be updated.

**Comment by cortx-admin** [comment]
For the convenience of the Seagate development team, this issue has been mirrored in a private Seagate Jira Server: https://jts.seagate.com/browse/EOS-27243. Note that community members will not be able to access that Jira server but that is not a problem since all activity in that Jira mirror will be copied into this GitHub issue.

**Comment by nkommuri** [comment]
@rkothiya  Can you please let us know which links are broken and also the curl command you were mentioning?

**Comment by rkothiya** [comment]
@nkommuri , will ping it to you on chat.

**Comment by hessio** [comment]
@rkothiya are you able to access the links yourself? I think the links should work for internal Seagate employees?

For people outside of Seagate network this guide should work

**Comment by johnbent** [comment]
Hey @hessio , I think it does not work for people outside of Seagate because of:
./install.sh -t http://cortx-storage.colo.seagate.com/releases/cortx/github/stable/centos-7.8.2003/292/prod/

Thanks to @rkothiya and @alfhad for helping diagnose this!

**Comment by johnbent** [comment]
All, I just noticed that this confluence document has been retired:

![image](https://user-images.githubusercontent.com/2047294/148255298-953a17fa-0fd7-434a-ba72-df0fa3b1714d.png)

So @rkothiya , where did you find a link to this document? We should remove/update that link.

**Comment by hessio** [comment]
Oh sorry I made a typo in my message yes I agree with you John this won't work for external people

**Comment by hessio** [comment]
cc: @shailesh-vaidya this is the issue I had been talking to you about in Teams, let's continue our discussion here

**Comment by johnbent** [comment]
@hessio and @shailesh-vaidya , this particular document has been retired. Why was it created in the first place? We should really just have 4 guides:
1. Run the OVA
2. Build code into containers
3. Deploy containerized code for S3+motr
4. Deploy containerized code for motr only

So why was this new confluence document created? Is it an attempt to make one of these 4? Or something else? In general, I worry that people create new confluence documents instead of editing/improving existing ones. This is another reason why it is better to keep instructions in github and not confluence. That way people will be less shy about proposing changes to existing documents and less likely to create new documents which overlap with existing ones.

**Comment by hessio** [comment]
Sure agreed @johnbent, as for the guide to generate the cortx all image [https://github.com/Seagate/cortx/blob/main/doc/community-build/docker/cortx-all/README.md](https://github.com/Seagate/cortx/blob/main/doc/community-build/docker/cortx-all/README.md) but now to include the built images to [this](https://github.com/Seagate/cortx-k8s/blob/stable/doc/cortx-aws-k8s-installation.md) document you have to use aws. Running kubernetes locally use a lot of resource, for local use most people use minikube 

Thanks to @r-wambui for finding this out for me. She's a great developer advocate too, this is really great work by her.

**Comment by nkommuri** [comment]
> All, I just noticed that this confluence document has been retired:
> 
> ![image](https://user-images.githubusercontent.com/2047294/148255298-953a17fa-0fd7-434a-ba72-df0fa3b1714d.png)
> 
> So @rkothiya , where did you find a link to this document? We should remove/update that link.

Hi @johnbent , This confluence page is retired after raising this issue. Closing this issue as it is no more valid.

**Comment by johnbent** [comment]
Thanks @nkommuri !

**Comment by cortx-admin** [comment]
> Chandradhar Raval commented in Jira Server:

Marking this Jira Closed as per above comment
