### ISSUE TITLE
missing example - fdmi_app_hello in FDMI doc

### ISSUE THREAD

**Issue by kiwionly2** [Seagate/cortx-motr#1372]
Hi, 

While browse through FDMI [document](https://github.com/Seagate/cortx-motr/blob/main/fdmi/plugins/motr-fdmi-app.md), I could not found example script `fdmi_app_hello` as state in the document which suppose in `cortx-motr/fdmi/plugins` directory.

![image](https://user-images.githubusercontent.com/77140436/148794569-c0979f03-6a47-436c-88bc-9e87a8a68517.png)

Any idea?

**Comment by cortx-admin** [comment]
For the convenience of the Seagate development team, this issue has been mirrored in a private Seagate Jira Server: https://jts.seagate.com/browse/EOS-27328. Note that community members will not be able to access that Jira server but that is not a problem since all activity in that Jira mirror will be copied into this GitHub issue.

**Comment by lia54** [comment]
Hi @kiwionly2, 
 
Thanks for pointing this out. 
I created a PR to add the FDMI application to the main branch in cortx-motr repo under the fdmi/plugins directory. This PR might take time to get merged. 

In the meanwhile, you can access the application in the same PR: 
https://github.com/Seagate/cortx-motr/pull/1373/files

Thanks!

**Comment by nkommuri** [comment]
@lia54  can you please resolve DCO/CLA issues of your PR.

**Comment by johnbent** [comment]
Hello @nkommuri , Liana did take care of CLA so I went ahead and merged. Thanks!

**Comment by cortx-admin** [comment]
> Chandradhar Raval commented in Jira Server:

Marking this Jira Closed based on above comment
