### ISSUE TITLE
Codacy integration broke

### ISSUE THREAD

**Issue by johnbent** [Seagate/cortx-motr#1391]
![image](https://user-images.githubusercontent.com/2047294/149584259-d8467ed1-2754-444c-93e2-dcdaa7a3ff62.png)

Somehow Codacy stopped working for this repo. @nkommuri and @mukul-seagate11 , can you please figure out an assignee for this?

**Comment by cortx-admin** [comment]
For the convenience of the Seagate development team, this issue has been mirrored in a private Seagate Jira Server: https://jts.seagate.com/browse/EOS-27559. Note that community members will not be able to access that Jira server but that is not a problem since all activity in that Jira mirror will be copied into this GitHub issue.

**Comment by nkommuri** [comment]
@mukul-seagate11  Can you please have a look at this and provide you feedback. Thanks.

**Comment by johnbent** [comment]
I sent an email to Codacy and it was a problem on their end. It has been fixed now. This issue can be closed. @nkommuri can you please close it in Jira and boardgenius will echo that here?

**Comment by cortx-admin** [comment]
> Chandradhar Raval commented in Jira Server:

Marking this Jira Closed based on above comments from [~535110]
