### ISSUE TITLE
incorrect link for motr/client.h overview section

### ISSUE THREAD

**Issue by kiwionly2** [Seagate/cortx-motr#1392]
I found the link for  `exascale E10 stack (see eiow.org). ` in **overview** section no longer valid, eiow.org had link to a spam site.

`https://opensfs.org` probably is the latest/correct link.

**Comment by cortx-admin** [comment]
For the convenience of the Seagate development team, this issue has been mirrored in a private Seagate Jira Server: https://jts.seagate.com/browse/EOS-27570. Note that community members will not be able to access that Jira server but that is not a problem since all activity in that Jira mirror will be copied into this GitHub issue.

**Comment by cortx-admin** [comment]
> Chandradhar Raval commented in Jira Server:

Marking this Jira Closed based on above comments
