### ISSUE TITLE
motr/examples set environment variable on comment header how to run section

### ISSUE THREAD

**Issue by kiwionly2** [Seagate/cortx-motr#1420]
Hi, 

For `example1.c` and `example2.c` in `motr/examples/`, the comment header for **how to run** 

```
*
* How to run:
* LD_LIBRARY_PATH=/work/cortx-motr/motr/.libs/                              
```

should it be `export LD_LIBRARY_PATH=/work/cortx-motr/motr/.libs/` instead ?

```
*
* How to run:
* export LD_LIBRARY_PATH=/work/cortx-motr/motr/.libs/                              
```

**Comment by cortx-admin** [comment]
For the convenience of the Seagate development team, this issue has been mirrored in a private Seagate Jira Server: https://jts.seagate.com/browse/EOS-28201. Note that community members will not be able to access that Jira server but that is not a problem since all activity in that Jira mirror will be copied into this GitHub issue.

**Comment by huanghua78** [comment]
Please note, this is on a single line.
So this setting will only take effect for this command.
It is not an issue.

Yes, of course, we can "export" this env. variable and that will take effect for this shell.

**Comment by cortx-admin** [comment]
> Chandradhar Raval commented in Jira Server:

Marking this Jira Closed based on above comment
