### ISSUE TITLE
Question related to m0trace.<number> after running example

### ISSUE THREAD

**Issue by kiwionly2** [Seagate/cortx-motr#1476]
I was try to run example2 in `motr/examples` folder.

Every time the program complete and exit, it will left a m0trace.<number> in the current directory.

Any idea what is that use for ?

**Comment by cortx-admin** [comment]
For the convenience of the Seagate development team, this issue has been mirrored in a private Seagate Jira Server: https://jts.seagate.com/browse/EOS-28784. Note that community members will not be able to access that Jira server but that is not a problem since all activity in that Jira mirror will be copied into this GitHub issue.

**Comment by r-wambui** [comment]
Hi @kiwionly2 I'll try and reproduce this.

**Comment by nkommuri** [comment]
Hi @kiwionly2 , those m0trace file contains motr client logs, which will be useful for debug purpose.

**Comment by kiwionly2** [comment]
@nkommuri  

I open the log file but seem like is not in plain text format, do we use any specific tool to view the logs ?

**Comment by huanghua78** [comment]
This is a Motr trace log file.
It is a binary file.
Motr tools are available to dump it into plain text format:
./utils/trace/m0trace
./utils/trace/m0tracedump


This m0trace.pid file can be removed.
Please refer to "lib/trace.h" for more information.

**Comment by cortx-admin** [comment]
> Chandradhar Raval commented in Jira Server:

Marking the Jira Closed based on above comments
