### ISSUE TITLE
Add FDMI demo

### ISSUE THREAD

**Issue by johnbent** [Seagate/cortx-motr#1535]
I just checked in the old FDMI demo that @nezzzu provided: https://github.com/Seagate/cortx-motr/tree/main/doc/fdmi_demo/demo-fdmi

It would be nice to add a link to it from https://github.com/Seagate/cortx-motr/blob/main/fdmi/plugins/motr-fdmi-app.md

**Comment by cortx-admin** [comment]
For the convenience of the Seagate development team, this issue has been mirrored in a private Seagate Jira Server: https://jts.seagate.com/browse/CORTX-29436. Note that community members will not be able to access that Jira server but that is not a problem since all activity in that Jira mirror will be copied into this GitHub issue.

**Comment by r-wambui** [comment]
@swatid-seagate Could you please look into this.

**Comment by swatid-seagate** [comment]
@johnbent  where do you expect the link to be added in the document? Can you also let me know what heading should I use for it?

**Comment by cortx-admin** [comment]
> Swati Dhotarkar commented in Jira Server:

[https://github.com/Seagate/cortx-motr/pull/1557] Please check this PR. I have added a link in "

How to create and test other FDMI Applications with examples " section.

**Comment by cortx-admin** [comment]
> Swati Dhotarkar commented in Jira Server:

PR raised against the issue : [https://github.com/Seagate/cortx-motr/pull/1557]

**Comment by nkommuri** [comment]
PR merged.

**Comment by cortx-admin** [comment]
> Chandradhar Raval commented in Jira Server:

Marking this Jira Closed and PR #1557 is merged now
