### ISSUE TITLE
Example of Variable length index key value

### ISSUE THREAD

**Issue by kiwionly2** [Seagate/cortx-motr#1547]
Hello,

I am looking for a way to put key value pair with variable length. 

So far the sample I found at `motr/examples/example2.c` is only show how to GET/PUT key value pair in fixed length. 

Is that any example that show GET/PUT variable length that I could refer to ?

**Comment by cortx-admin** [comment]
For the convenience of the Seagate development team, this issue has been mirrored in a private Seagate Jira Server: https://jts.seagate.com/browse/CORTX-29512. Note that community members will not be able to access that Jira server but that is not a problem since all activity in that Jira mirror will be copied into this GitHub issue.

**Comment by nkommuri** [comment]
@kiwionly2  Can you please try changing example2.c for variable length.
Can I request you to join the following cortx-motr slack channel for any such queries instead of opening a issue? Thanks.
https://cortxcommunity.slack.com/archives/C019S0SGWNQ

**Comment by kiwionly2** [comment]
Hi @nkommuri, I will close this issue and discuss in slack.

thanks !

**Comment by cortx-admin** [comment]
> Chandradhar Raval commented in Jira Server:

Marking this issue closed and corresponding github ticket is Closed
