### ISSUE TITLE
libmotrclient ? 

### ISSUE THREAD

**Issue by kiwionly2** [Seagate/cortx-motr#1551]
Hello, 

Is that any client library for motr ( or one in future ) which contain high level motr function e.g. put_index, get_index read, write etc ? (e.g. [libevent ](https://libevent.org/) or [hiredis](https://github.com/redis/hiredis) for redis equivalent. )

With libmotr, still need to code in pretty low detail level even with the help from the [developer guide](https://github.com/kiwionly2/cortx-motr/blob/main/doc/motr-developer-guide.md), and also `motr/examples` folder. 

If that is one lib, this would make motr much easier to code and reuse, also could easier to understand motr by looking at the API, and it could also be a single source reference for developers. ( I found the samples in the `motr/examples`  have a lot of samples but is provided same functionality )

**Comment by cortx-admin** [comment]
For the convenience of the Seagate development team, this issue has been mirrored in a private Seagate Jira Server: https://jts.seagate.com/browse/CORTX-29521. Note that community members will not be able to access that Jira server but that is not a problem since all activity in that Jira mirror will be copied into this GitHub issue.

**Comment by johnbent** [comment]
Hey @kiwionly2, I believe that Maestro is what you are looking for. FYI @nezzzu who I believe is the primary author of Maestro. 

Here is Maestro: https://github.com/Seagate/cortx-mio

And I submitted a PR to cortx-motr so that future people should be able to more easily find this: https://github.com/Seagate/cortx-motr/pull/1552/files

**Comment by kiwionly2** [comment]
Hi @johnbent, most of the samples I found is using command line to interact with motr ( same like Maestro and go binding ).

Actually I was looking for a client lib which could use to code. This could provided more way to integration with motr, e.g. could use to create a RPC service, or write a motr performance test script.

**Comment by chandradharraval** [comment]
Hi @johnbent, @kiwionly2,
I see one PR [[https://github.com/Seagate/cortx-motr/pull/1552/](https://github.com/Seagate/cortx-motr/pull/1552/files)] is merged. Do we still need more information for this ticket?

**Comment by johnbent** [comment]
Thanks @chandradharraval . I think we can close.

@kiwionly2 , if you are still having problems or think this isn't sufficient, please feel free to re-open this issue.

**Comment by cortx-admin** [comment]
> Chandradhar Raval commented in Jira Server:

Marking this Jira closed based on above comments

**Comment by kiwionly2** [comment]
@johnbent

Sure, actually after I spend some time look into `cortx-mio` and others, I have more understand how the thing works, I realize I got question mostly is because of not familiar with and motr api and C language.
