### ISSUE TITLE
[Codacy code cleanup] occurrence: 107 pattern: Warn when spacing between a list item's bullet and its content violates

### ISSUE THREAD

**Issue by rkothiya** [Seagate/cortx-motr#1611]
### Problem

We see 107 occurrence of pattern, "Warn when spacing between a list item's bullet and its content violates".

### Expected behavior

We should not be getting these warnings

### How to reproduce

Not applicable 

### Deployment information

Static code analysis warnings.

**Comment by cortx-admin** [comment]
For the convenience of the Seagate development team, this issue has been mirrored in a private Seagate Jira Server: https://jts.seagate.com/browse/CORTX-30756. Note that community members will not be able to access that Jira server but that is not a problem since all activity in that Jira mirror will be copied into this GitHub issue.

**Comment by rkothiya** [comment]
The pattern has been disabled by documentation team following the footsteps of other components in our project.

**Comment by cortx-admin** [comment]
> Rinku Kothiya commented in Jira Server:

The pattern was disabled by following the footsteps of other components/teams.

**Comment by cortx-admin** [comment]
> Rinku Kothiya commented in Jira Server:

.

**Comment by cortx-admin** [comment]
> Rinku Kothiya commented in Jira Server:

We no longer see this warning in codacy dashboard.
