### ISSUE TITLE
[Codacy code cleanup] occurrence: 26 pattern: Variable 'var' is reassigned value before the old one has been used

### ISSUE THREAD

**Issue by rkothiya** [Seagate/cortx-motr#1614]
### Problem

We see 26 occurrence of pattern, "Variable 'var' is reassigned value before the old one has been used".

### Expected behavior

We should not be getting these warnings

### How to reproduce

Not applicable 

### Deployment information

Static code analysis warnings.

**Comment by cortx-admin** [comment]
For the convenience of the Seagate development team, this issue has been mirrored in a private Seagate Jira Server: https://jts.seagate.com/browse/CORTX-30759. Note that community members will not be able to access that Jira server but that is not a problem since all activity in that Jira mirror will be copied into this GitHub issue.

**Comment by cortx-admin** [comment]
> Rinku Kothiya commented in Jira Server:

Codacy warning

**Comment by cortx-admin** [comment]
> Rinku Kothiya commented in Jira Server:

It was decided that for warnings in c files, the bugs will be assigned to specific team which own that component.

**Comment by cortx-admin** [comment]
> Rinku Kothiya commented in Jira Server:

It was decided that for warnings in c files, the bugs will be assigned to specific team which own that component.

**Comment by cortx-admin** [comment]
> Rinku Kothiya commented in Jira Server:

reason stated in the above comment.
