### ISSUE TITLE
[Codacy code cleanup] occurrence: 15 pattern: var was modified in a subshell. That change might be lost

### ISSUE THREAD

**Issue by rkothiya** [Seagate/cortx-motr#1615]
### Problem

We see 15 occurrence of pattern, "var was modified in a subshell. That change might be lost".

### Expected behavior

We should not be getting these warnings 

### How to reproduce

Fire the below command to list all the warnings : 

`# shellcheck   -x  <file name>`

### Deployment information

Install the shellcheck package. For example to install it on Fedora/RHEL/centos you can fire : 

` # yum -y install ShellCheck`

### Additional information

Following files contains this warnings 

./rpc/it/linux_kernel/rpcload.sh
./scripts/install/opt/seagate/cortx/motr/libexec/motr_data_recovery.sh

**Comment by cortx-admin** [comment]
For the convenience of the Seagate development team, this issue has been mirrored in a private Seagate Jira Server: https://jts.seagate.com/browse/CORTX-30760. Note that community members will not be able to access that Jira server but that is not a problem since all activity in that Jira mirror will be copied into this GitHub issue.

**Comment by shailesh-vaidya** [comment]
Closing as an obsolete
