### ISSUE TITLE
CORTX inclusive words scan (alex) fail to run when PR is build

### ISSUE THREAD

**Issue by kiwionly2** [Seagate/cortx-motr#1630]
### Problem

When PR is build, Alex is always fail with error below:

![image](https://user-images.githubusercontent.com/77140436/163569442-d3b7ebc4-832e-4d82-9fd1-a68c0e8ea2bd.png)

### Expected behavior

Alex build should be able to run without issue.

### How to reproduce

Commit a code to the branch belong to a PR.

This will trigger build and running Alex.

### Deployment information

n/a

**Comment by cortx-admin** [comment]
For the convenience of the Seagate development team, this issue has been mirrored in a private Seagate Jira Server: https://jts.seagate.com/browse/CORTX-30803. Note that community members will not be able to access that Jira server but that is not a problem since all activity in that Jira mirror will be copied into this GitHub issue.

**Comment by chandradharraval** [comment]
This issue will be addressed via [https://jts.seagate.com/browse/CORTX-30785](url) by RE team

**Comment by nkommuri** [comment]
Addressed by PR https://github.com/Seagate/cortx-motr/pull/1729

**Comment by cortx-admin** [comment]
> Chandradhar Raval commented in Jira Server:

Marking this issue Resolved and the same is fixed via [https://github.com/Seagate/cortx-motr/pull/1729]

**Comment by cortx-admin** [comment]
> Chandradhar Raval commented in Jira Server:

[~935494] - Can you get it validated and then close this JIRA?

**Comment by cortx-admin** [comment]
> Chandradhar Raval commented in Jira Server:

Issues was resolved. Closing the same now as no update from last 5 days
