### ISSUE TITLE
mcp hangs when motr i/o op returns an error

### ISSUE THREAD

**Issue by andriytk** [Seagate/cortx-motr#1681]
When some motr i/o operation returns an error, `go/mio/mio.go:doIO()` function just hangs.

**Comment by andriytk** [comment]
Fixed by https://github.com/Seagate/cortx-motr/pull/1655.

**Comment by cortx-admin** [comment]
For the convenience of the Seagate development team, this issue has been mirrored in a private Seagate Jira Server: https://jts.seagate.com/browse/CORTX-31023. Note that community members will not be able to access that Jira server but that is not a problem since all activity in that Jira mirror will be copied into this GitHub issue.

**Comment by cortx-admin** [comment]
> Chandradhar Raval commented in Jira Server:

Marking this issue Closed and corresponding github issue is closed via  [#1655|https://github.com/Seagate/cortx-motr/pull/1655]
