### ISSUE TITLE
Codacy badge not rendering correctly

### ISSUE THREAD

**Issue by johnbent** [Seagate/cortx-motr#1705]
### Problem

The codacy badge in the top-level README is not rendering correctly:
![image](https://user-images.githubusercontent.com/2047294/165827588-301b5bab-46f0-4a39-9f27-1d0c3b3ec568.png)

### Expected behavior

It should look like this:
![image](https://user-images.githubusercontent.com/2047294/165827626-56c7bb9e-cb55-4681-b4cb-288d9b55700d.png)

### How to reproduce

Load https://github.com/Seagate/cortx-motr/blob/main/README.rst and look at the top of the page.

### Deployment information

Any web browser

**Comment by johnbent** [comment]
@swatid-seagate , can you try to fix this please?

**Comment by cortx-admin** [comment]
For the convenience of the Seagate development team, this issue has been mirrored in a private Seagate Jira Server: https://jts.seagate.com/browse/CORTX-31057. Note that community members will not be able to access that Jira server but that is not a problem since all activity in that Jira mirror will be copied into this GitHub issue.

**Comment by cortx-admin** [comment]
> Swati Dhotarkar commented in Jira Server:

Sure John, I will work on it. Added the task to my todo list.

**Comment by cortx-admin** [comment]
> Swati Dhotarkar commented in Jira Server:

Worked on the issue. Raised the PR : https://github.com/Seagate/cortx-motr/pull/1709

**Comment by cortx-admin** [comment]
> Chandradhar Raval commented in Jira Server:

Marking this Jira Closed and corresponding PR is merged
