### ISSUE TITLE
Codacy warnings, "Defined from star imports"

### ISSUE THREAD

**Issue by mukul-seagate11** [Seagate/cortx-motr#1822]
#### Currently on:
+ **Commit**:  40ca11364a02bca9b3f584e2b43647e60fd9a4e4
+ **File**:    [scripts/addb-py/chronometry/addb2db.py](https://github.com/Seagate/cortx-motr/blob/40ca11364a02bca9b3f584e2b43647e60fd9a4e4/scripts/addb-py/chronometry/addb2db.py)
+ **LineNum**: [112](https://github.com/Seagate/cortx-motr/blob/40ca11364a02bca9b3f584e2b43647e60fd9a4e4/scripts/addb-py/chronometry/addb2db.py#L112)

**Comment by cortx-admin** [comment]
For the convenience of the Seagate development team, this issue has been mirrored in a private Seagate Jira Server: https://jts.seagate.com/browse/CORTX-31631. Note that community members will not be able to access that Jira server but that is not a problem since all activity in that Jira mirror will be copied into this GitHub issue.

**Comment by cortx-admin** [comment]
> Chandradhar Raval commented in Jira Server:

Closing this issue as corresponding Github issue is closed now
