### ISSUE TITLE
[Codacy code cleanup] occurrence: 5 pattern: bare-except

### ISSUE THREAD

**Issue by rkothiya** [Seagate/cortx-motr#1824]
### Problem

We see 5 occurrence of pattern, "bare-except"

### Expected behavior

We should not be getting these warnings

### How to reproduce

``` # pylint <filename> ``` 

### Deployment information

``` # yum install pylint ```

### Additional information

**Following files contains this warnings :**

scripts/addb-py/chronometry/s3_req.py
scripts/addb-py/chronometry/addb2db.py
scripts/addb-py/chronometry/hist.py
scripts/addb-py/chronometry/task_queue/tasks.py

**Comment by cortx-admin** [comment]
For the convenience of the Seagate development team, this issue has been mirrored in a private Seagate Jira Server: https://jts.seagate.com/browse/CORTX-31633. Note that community members will not be able to access that Jira server but that is not a problem since all activity in that Jira mirror will be copied into this GitHub issue.

**Comment by cortx-admin** [comment]
> Rinku Kothiya commented in Jira Server:

codacy warning

**Comment by cortx-admin** [comment]
> Rinku Kothiya commented in Jira Server:

All the warnings under chronometry were disabled because this code was shifted in another repository seagate-tools.

So these changes are no longer needed.

**Comment by cortx-admin** [comment]
> Rinku Kothiya commented in Jira Server:

Due to reason mentioned in the above comment
