### ISSUE TITLE
[Codacy code cleanup] occurrence: 5 pattern: unidiomatic-typecheck

### ISSUE THREAD

**Issue by rkothiya** [Seagate/cortx-motr#1825]
### Problem

We see 5 occurrence of pattern, "unidiomatic-typecheck"

### Expected behavior

We should not be getting these warnings

### How to reproduce

``` # pylint scripts/provisioning/plugins/pretty_print.py  ```

### Deployment information

``` # yum install pylint ```

### Additional information

Following file contains this warnings :

scripts/provisioning/plugins/pretty_print.py

**Comment by cortx-admin** [comment]
For the convenience of the Seagate development team, this issue has been mirrored in a private Seagate Jira Server: https://jts.seagate.com/browse/CORTX-31635. Note that community members will not be able to access that Jira server but that is not a problem since all activity in that Jira mirror will be copied into this GitHub issue.

**Comment by rkothiya** [comment]
Already fix via : 
https://github.com/Seagate/cortx-motr/pull/2005

**Comment by cortx-admin** [comment]
> Rinku Kothiya commented in Jira Server:

duplicate of CORTX-33681

**Comment by cortx-admin** [comment]
> Rinku Kothiya commented in Jira Server:

duplicate of CORTX-33681

**Comment by cortx-admin** [comment]
> Rinku Kothiya commented in Jira Server:

duplicate of CORTX-33681
