### ISSUE TITLE
[Codacy code cleanup] occurrence: 5 pattern: unused-variable

### ISSUE THREAD

**Issue by rkothiya** [Seagate/cortx-motr#1826]
### Problem

We see 5 occurrence of pattern, "unused-variable"

### Expected behavior

We should not be getting these warnings

### How to reproduce

``` # pylint <filename> ```

### Deployment information

``` # yum install pylint ``` 

### Additional information

**Following files contains this warnings :**

scripts/install/opt/seagate/cortx/motr/bin/motr_mini_prov.py
scripts/addb-py/chronometry/queues.py
scripts/addb-py/chronometry/addb2db.py
scripts/addb-py/chronometry/task_queue/tasks.py
scripts/addb-py/chronometry/req_utils.py
scripts/addb-py/filter.py
scripts/provisioning/plugins/pretty_print.py

**Comment by cortx-admin** [comment]
For the convenience of the Seagate development team, this issue has been mirrored in a private Seagate Jira Server: https://jts.seagate.com/browse/CORTX-31636. Note that community members will not be able to access that Jira server but that is not a problem since all activity in that Jira mirror will be copied into this GitHub issue.

**Comment by cortx-admin** [comment]
> Chandradhar Raval commented in Jira Server:

Fixing can be done for all files except "scripts/addb-py/chronometry/" directory.

We plan to remove scripts/addb-py/chronometry/ from the cortx-motr repo

**Comment by cortx-admin** [comment]
> Rinku Kothiya commented in Jira Server:

Following patch should address the issue:
[https://github.com/Seagate/cortx-motr/pull/2151]

**Comment by shailesh-vaidya** [comment]
Closing as an obsolete
