### ISSUE TITLE
[Codacy code cleanup] occurrence: 4 pattern: no-value-for-parameter

### ISSUE THREAD

**Issue by rkothiya** [Seagate/cortx-motr#1827]
### Problem

We see 4 occurrence of pattern : "no-value-for-parameter"

### Expected behavior

We should not be getting these warnings

### How to reproduce

``` # pylint <filename> ```

### Deployment information

``` # yum install pylint ```

### Additional information

**Following files contains this warnings :**

scripts/addb-py/chronometry/task_queue/task_queue.py
scripts/addb-py/chronometry/md_req.py
scripts/addb-py/chronometry/io_req.py

**Comment by cortx-admin** [comment]
For the convenience of the Seagate development team, this issue has been mirrored in a private Seagate Jira Server: https://jts.seagate.com/browse/CORTX-31637. Note that community members will not be able to access that Jira server but that is not a problem since all activity in that Jira mirror will be copied into this GitHub issue.

**Comment by shailesh-vaidya** [comment]
Closing as an obsolete
