### ISSUE TITLE
[Codacy code cleanup] occurrence: 5 pattern: pep257 tool

### ISSUE THREAD

**Issue by rkothiya** [Seagate/cortx-motr#1858]
### Problem

We see 5 occurrence of pattern : "pep257 tool"

Under this heading we are seeing 2 different warnings one with missing line and other missing doc string. 

### Expected behavior

We should not be getting these warnings

### How to reproduce

``` # pycodestyle ./scripts/install/opt/seagate/cortx/motr/bin/motr_mini_prov.py | grep blank ``` 

### Deployment information

``` # yum install python3-pycodestyle.noarch ```

### Additional information

scripts/install/opt/seagate/cortx/motr/bin/motr_mini_prov.py

**Comment by cortx-admin** [comment]
For the convenience of the Seagate development team, this issue has been mirrored in a private Seagate Jira Server: https://jts.seagate.com/browse/CORTX-32081. Note that community members will not be able to access that Jira server but that is not a problem since all activity in that Jira mirror will be copied into this GitHub issue.

**Comment by rkothiya** [comment]
Pull request https://github.com/Seagate/cortx-motr/pull/1859 was created to address this, but in the codacy meeting it was discussed that fixing this throws up another warning, hence we have put this on hold.

**Comment by shailesh-vaidya** [comment]
Closing as an obsolete
