### ISSUE TITLE
list of unit test failed

### ISSUE THREAD

**Issue by kimika88** [Seagate/cortx-motr#1950]
### Problem

scripts/m0 run-ut -l
----- run_ut -l -----
opening /dev/lnet failed: No such file or directory
hint: the kernel modules may not be loaded
IOC_LIBCFS_GET_NI error 2: No such file or directory
libm0-ut
addb2-base
addb2-consumer

### Expected behavior

Expected to list all the unit tests immediately after the command

### How to reproduce

Followed the quick start guide to install https://github.com/Seagate/cortx-motr/blob/main/doc/Quick-Start-Guide.rst
[root@ssc-vm-g4-rhev4-1317 cortx-motr]# fi_info --version
fi_info: 1.11.2
libfabric: 1.11.2
libfabric api: 1.11
[root@ssc-vm-g4-rhev4-1317 cortx-motr]# cat /etc/redhat-release
CentOS Linux release 7.9.2009 (Core)

### Deployment information

Version is 
[root@ssc-vm-g4-rhev4-1317 cortx-motr]# git describe --tags
2.0.0-845-7-g91f77a1

**Comment by cortx-admin** [comment]
For the convenience of the Seagate development team, this issue has been mirrored in a private Seagate Jira Server: https://jts.seagate.com/browse/CORTX-33118. Note that community members will not be able to access that Jira server but that is not a problem since all activity in that Jira mirror will be copied into this GitHub issue.

**Comment by kimika88** [comment]
Solved by running the following commands:

```
modprobe lnet
lctl network up

```

**Comment by cortx-admin** [comment]
> Chandradhar Raval commented in Jira Server:

Closing this issue as corresponding Github issue is closed
