### ISSUE TITLE
Disable alternative pool versions by default

### ISSUE THREAD

**Issue by andriytk** [Seagate/cortx-motr#1958]
In case of some failure, we want the I/O to be done in the base pool version in the degraded mode always without switching to the alternative pool version. Later, when we introduce the side pool versions, we will do the degraded I/O in them and use them for faster SNS-recovery, which will try to recover only the objects which have the side pool versions instead of traversing all objects in the cluster.

Relates to https://github.com/Seagate/cortx-hare/pull/2123.

**Comment by cortx-admin** [comment]
For the convenience of the Seagate development team, this issue has been mirrored in a private Seagate Jira Server: https://jts.seagate.com/browse/CORTX-33537. Note that community members will not be able to access that Jira server but that is not a problem since all activity in that Jira mirror will be copied into this GitHub issue.

**Comment by cortx-admin** [comment]
> Andriy Tkachuk commented in Jira Server:

Ready for review at https://github.com/Seagate/cortx-motr/pull/1959

**Comment by cortx-admin** [comment]
> Chandradhar Raval commented in Jira Server:

https://github.com/Seagate/cortx-motr/issues/1958 is merged
