### ISSUE TITLE
dix: return obj-version and number of replicas on get

### ISSUE THREAD

**Issue by andriytk** [Seagate/cortx-motr#2117]
Background:

S3-object deletion is done in two stages: online and offline. (See more at https://github.com/Seagate/cortx-rgw/issues/7.) In the online stage, we just insert the tombstones into the bucket index. In the offline stage, which is done by GC, after the object data is deleted, we need to cleanup the tombstones also. This tombstones cleanup mechanism is a bit tricky, it's done in two phases (in general case), and we need some new operations from Motr to support this.

The requirement for the tombstones cleanup is that there should be no replica (online or offline) with any stale data left after it. How this can happen? Well, if some replica was offline when the tombstones were inserted during the online deletion stage, it still will contain the stale data which may come up later when the replica goes online after the tombstones have been cleaned up on all other replicas already.

So in order to make sure that there are no stale data left in any of the replicas, we perform the tombstones cleanup in two phases: 1) make sure all replicas have the tombstones (or some newer obj-version); 2) delete the tombstones.

Requirement:

The very 1st step GC always does is reading of the object metadata from the bucket index. If it happens to read the tombstones values from the replicas, it should return the obj-version of the tombstones (needed in the following cleanup) and the number of replicas replied (e.g. 2 of 3, or 3 of 3).

Use-case:

If the number of replicas replied with the same obj-version equals to the total number of replicas (e.g. 3 of 3), we can skip the 1st phase of the tombstones cleanup process entirely and just proceed with the 2nd step - delete the tombstones. We expect that to be true in most of the cases.

**Comment by cortx-admin** [comment]
For the convenience of the Seagate development team, this issue has been mirrored in a private Seagate Jira Server: https://jts.seagate.com/browse/CORTX-34132. Note that community members will not be able to access that Jira server but that is not a problem since all activity in that Jira mirror will be copied into this GitHub issue.

**Comment by huanghua78** [comment]
> S3-object deletion is done in two stages: online and offline. In the online stage, we just insert the tombstones into the bucket index. In the offline stage, which is done by GC, we need to cleanup the tombstones. This cleanup is a bit tricky, it's done in two phases (in general case), and we need some new operations from Motr to support this.


"S3-object deletion" is ambiguous.  In S3 object deletion, one of the step is to do DIX DEL operation to delete metadata (the mapping from s3 object to Motr object, and other things) stored in the Key/Val pair.

"online and offline", is easy to be confused with "node/service online" and "node/service offline", especially when you mentioned these teams in the second paragraph.


"In the online stage, we just insert the tombstones into the bucket index". As my understanding, we do a DIX DEL operation to delete some key/val (which contains metadata of s3 object), and under the hood, this DIX DEL operation inserts a TOMBSTONE flag in this key/val instead of physically deleting it.  (Maybe we can remove the actually value part from underlying btree and leave the value part as empty. This is already done, right?)


"In the offline stage, which is done by GC, we need to cleanup the tombstones."  This is to physically delete the key/val pair (along with the TOMBSTONE flag) from the underlying btree.

**Comment by huanghua78** [comment]
> The very 1st step GC always does is reading of the object metadata from the bucket index. If it happens to read the tombstones values from the replicas, it should return the obj-version of the tombstones (needed in the following cleanup) and the number of replicas replied (e.g. 2 of 3, or 3 of 3).


Can this number be 1?

**Comment by huanghua78** [comment]
> If the number of replicas replied with the same obj-version equals to the total number of replicas (e.g. 3 of 3), we can skip the 1st phase of the tombstones cleanup process entirely and just proceed with the 2nd step - delete the tombstones. We expect that to be true in most of the cases.



What if the number of replicas are less than 3?
How to achieve "1) make sure all replicas have the tombstones (or some newer obj-version);"?
So this is the task to implement something new in Motr to support this?

**Comment by andriytk** [comment]
Well, maybe online/offline terms for the deletion stages here are a bit confusing, indeed. But I could not find the better terms to use. In some other documents, people use sync/async terms, but they seem even more confusing to me.

> Maybe we can remove the actually value part from underlying btree and leave the value part as empty. This is already done, right?

Not sure.

We can run the 2-phase cleanup procedure of the object metadata from the bucket index in the online stage, yes. But 1) this will impact the performance of the online deletion stage (and we want it to be very fast); 2) this will impose the requirement of all replicas to be online for the deletion operation to succeed. I don't think that the users/customers will be happy about it.

**Comment by shailesh-vaidya** [comment]
Closing as an obsolete
