### ISSUE TITLE
dix: introduce cas-put by obj-version operation

### ISSUE THREAD

**Issue by andriytk** [Seagate/cortx-motr#2118]
This is needed for the 1st phase of tombstones cleanup procedure, see more at https://github.com/Seagate/cortx-motr/issues/2117.

Motr client should be able to put the tombstone of specific obj-version into the bucket index. On the server side, the insert should happen only if there is some older obj-version present or there is no value at all. The same or newer obj-versions should not be updated.

The operation should return success only if all replicas were processed and there is no replica left which would have some older object version in it.

**Comment by cortx-admin** [comment]
For the convenience of the Seagate development team, this issue has been mirrored in a private Seagate Jira Server: https://jts.seagate.com/browse/CORTX-34133. Note that community members will not be able to access that Jira server but that is not a problem since all activity in that Jira mirror will be copied into this GitHub issue.

**Comment by trshaffer** [comment]
This should be the current behavior for versioned delete (newer version wins, insert tombstone rather than `-ENOENT`). As for the replica requirement, I think the new quorum functionality could be used for this with quorum set to N+K. It might be helpful to add another special quorum value like `QUORUM_ALL`?

**Comment by andriytk** [comment]
> providing a specific version may be difficult with the current Motr client interface

Yeah, the client somehow needs to provide the existing tombstones obj-version he got on GET. The point here is to make sure that all replicas have the tombstone of the same version which already exists. If we generate some new version for the tombstones in this step, it might re-write the new object data which user can write in a meanwhile.

**Comment by shailesh-vaidya** [comment]
Closing as an obsolete
