### ISSUE TITLE
dix: introduce cas-delete by obj-version operation

### ISSUE THREAD

**Issue by andriytk** [Seagate/cortx-motr#2119]
This is needed for the 2nd phase of the tombstones cleanup procedure, see more at https://github.com/Seagate/cortx-motr/issues/2117.

Motr client should be able to delete by specific obj-version from the bucket index. It should perform the actual deletion, not insertion of the tombstones like in normal delete operations.

On the server side, the deletion should happen only if the exact obj-version is present. Newer obj-versions should not be touched. If an older obj-version is present (unlikely), an error should be returned.

The operation should return success only if all replicas were processed and there is no replica left which would have the specified or older object version in it.

**Comment by cortx-admin** [comment]
For the convenience of the Seagate development team, this issue has been mirrored in a private Seagate Jira Server: https://jts.seagate.com/browse/CORTX-34134. Note that community members will not be able to access that Jira server but that is not a problem since all activity in that Jira mirror will be copied into this GitHub issue.

**Comment by trshaffer** [comment]
DIX can currently do unconditional tombstone delete via delete with zero version. This looks like it would need to be a new operation in CAS and DIX, along with client interface.

**Comment by shailesh-vaidya** [comment]
Closing as an obsolete
