### ISSUE TITLE
dix: make index creation/deletion operations fault-tolerant

### ISSUE THREAD

**Issue by andriytk** [Seagate/cortx-motr#2142]
Currently, we cannot create or delete indexes if some CAS server is down. This means that the user cannot create or delete buckets in such a case. This should be improved.

It seems, we just need to enable quorum+versioning on meta-indexes and CROW in CAS to make this working.

**Comment by cortx-admin** [comment]
For the convenience of the Seagate development team, this issue has been mirrored in a private Seagate Jira Server: https://jts.seagate.com/browse/CORTX-34188. Note that community members will not be able to access that Jira server but that is not a problem since all activity in that Jira mirror will be copied into this GitHub issue.

**Comment by shailesh-vaidya** [comment]
Closing as an obsolete
