### ISSUE TITLE
HA service fails in Motr singlenode sanity test

### ISSUE THREAD

**Issue by hessio** [Seagate/cortx-motr#464]
Problem: User runs command `sudo ./scripts/m0 run-st 52motr-singlenode-sanity` and they receive an error that HA service fails

Attached is an image of the error:

![motr error](https://user-images.githubusercontent.com/23244853/108700530-a2fdf680-74fe-11eb-8726-507acade0e93.png)

**Comment by johnbent** [comment]
@hessio , did you get this sorted yet?  I moved it to cortx-motr.  Let me know if you think it's better located in parent.

**Comment by hessio** [comment]
You can run without any issues. This is a known issue, I believe it is a Motr error. @huanghua78 can you please advise here as we discussed on Teams to make this issue.

**Comment by yanqingfu** [comment]
encountered the same issue

**Comment by nkommuri** [comment]
This has been addressed through https://jts.seagate.com/browse/EOS-21987.  This failure is expected.

Sometimes motr-server-ha can FAIL during shutdown of the service, due to
order in which services are being stopped and their interdependency.
FAILURE of motr-server-ha during shutdown is expected, as it is a dummy HA
and does not know the logic and events generated in other services.
This will not be an issue with clustered environment, as HAX will have control over the services.

**Comment by cortx-admin** [comment]
> Nagakishore Kommuri commented in Jira Server:

Linked Github issue closed.

**Comment by cortx-admin** [comment]
> Nagakishore Kommuri commented in Jira Server:

.

**Comment by cortx-admin** [comment]
> Nagakishore Kommuri commented in Jira Server:

.
