### ISSUE TITLE
init script failure at [motr-build : build Lustre rpms]

### ISSUE THREAD

**Issue by TechWriter-Mayur** [Seagate/cortx-motr#542]
I followed the [S3 Server QSG](https://github.com/Seagate/cortx-s3server/blob/main/docs/CORTX-S3%20Server%20Quick%20Start%20Guide.md) and I observed that it is failing to build Lustre rpm in the Motr init script. Please find the attached log.
[rpmerror1.txt](https://github.com/Seagate/cortx-s3server/files/6202636/rpmerror1.txt)

**Comment by mukul-seagate11** [comment]
@team, please address the issue reported

**Comment by madhavemuri** [comment]
TASK [base-os : install kernel-devel for the current kernel] *************************************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "No package matching 'kernel-devel-3.10.0-1062.el7.x8                                                          6_64' found available, installed or updated", "rc": 126, "results": ["No package matching 'kernel-devel-3.10.0                                                          -1062.el7.x86_64' found available, installed or updated"]}
...ignoring
msg:  No package matching 'kernel-devel-3.10.0-1062.el7.x86_64' found available, installed or updated
results:  No package matching 'kernel-devel-3.10.0-1062.el7.x86_64' found available, installed or updated



Issue is due to non-availability of kernel-devel rpms.
I think currently these rpms are not available in default centos 7 location.

@mukul-seagate11 : Can you work with RE team about it and i would suggest to use centos 7.8, which have these rpms at default centos repo and is the one being used by cortx team.

**Comment by huanghua78** [comment]
I think you are running CentOS 7.7, and this version of CentOS is obsoleted.
Please install "kernel-devel-3.10.0-1062.el7.x86_64" manually from https://vault.centos.org/7.7.1908/os/x86_64/Packages/

**Comment by huanghua78** [comment]
CentOS 7.8 is also obsoleted.
You have to go to "https://vault.centos.org/7.8.2003/os/x86_64/Packages/" and install this rpm manually.

**Comment by TechWriter-Mayur** [comment]
Thank you for your response. I checked and verified and that I was having the same Kernel version. So, I had uninstall the Kernel-devel and reinstall the specific version manually and it worked.

Thanks again for all your help. 
![s3](https://user-images.githubusercontent.com/64980335/112646857-eb963000-8e6d-11eb-94e2-50f8730c324c.PNG)

**Comment by johnbent** [comment]
Thanks all.  Closing this issue.
